# Linear Algebra - Anton Rorres
## Applications with Python

## Determinants by expansion of cofactors

The determinant of a square matrix $M$ of size $N$ can be calculated by the sum of each element in a row or column multiplied by its equivalent entry in the cofactor matrix $C$.

$|M| = \sum_{i=1}^{N} a_{ij}C_{ij} = \sum_{j=1}^{N} a_{ij} C_{ij} \space \forall i,j$

$C_{ij} = (-1)^{i+j} M_{ij}$

In [42]:
import numpy as np

M = np.matrix([[1,2,0],
               [3,1,1],
               [1,4,2]])

In [3]:
D = np.linalg.det(M)
D

-12.0

In [47]:
# Let's calculate the cofactor matrix

C=np.zeros((3,3))
for i in range(3):
    for j in range(3):
        mult = (-1)**(i+j)
        m = np.delete(M, (i), axis=0)
        m = np.delete(m, (j), axis=1)
        C[i,j] = mult * np.linalg.det(m)

In [48]:
C

array([[ -2.,  -5.,  11.],
       [ -4.,   2.,  -2.],
       [  2.,  -1.,  -5.]])

In [68]:
determinant_list = []
d=0

#check for all rows
for j in range(3):
    for i in range(3):
        d += M[j,i]*X[j,i]
        if i == 2:
            determinant_list.append(d)
            d = 0

#check for all columns
for j in range(3):
    for i in range(3):
        d += M[i,j]*X[i,j]
        if i == 2:
            determinant_list.append(d)
            d = 0

In [70]:
determinant_list == D

array([ True,  True,  True,  True,  True,  True], dtype=bool)

## Cramer Rule

Let $Ax=b$ be a linear system of n equations, such that $det(A) \neq 0$. This solution is such that:

$x_1 = \frac{\large det(A_1)}{\large det(A)}, \dots, x_n = \frac{\large det(A_n)}{\large det(A)}$

In [77]:
A = np.matrix([[1,2,3],
               [3,1,1],
               [1,4,2]])

b = np.matrix([[4],
               [1],
               [2]])

x = np.linalg.inv(A).dot(b)

In [73]:
x

matrix([[-0.0952381 ],
        [-0.23809524],
        [ 1.52380952]])

In [79]:
A.dot(x) 

matrix([[ 4.],
        [ 1.],
        [ 2.]])

In [84]:
M1 = A.copy()
M1[:,0] = b
x1 = np.linalg.det(M1)/np.linalg.det(A)

M2 = A.copy()
M2[:,1] = b
x2 = np.linalg.det(M2)/np.linalg.det(A)

M3 = A.copy()
M3[:,2] = b
x3 = np.linalg.det(M3)/np.linalg.det(A)

In [85]:
x1, x2, x3

(-0.095238095238095233, -0.23809523809523814, 1.5238095238095237)